### PR TITLE
Added icon for ReVanced Manager

### PR DESCRIPTION
**Pull request by N0-0NE-Dev**

### CODE REVIEW

**Comment by rufus582** [comment]
Thanks for contributing, but next time pls make sure you're commits aren't messed up, as it is now, so we can directly merge the pr, instead of committing it manually

**Comment by rufus582** [comment]
https://github.com/TeamFiles/Lawnicons/commit/3ad48c0ec5624a71e7c24712a09d6e242e356629

**Comment by N0-0NE-Dev** [comment]
> Thanks for contributing, but next time pls make sure you're commits aren't messed up, as it is now, so we can directly merge the pr, instead of committing it manually

Sorry for that.

**Comment by rufus582** [comment]
> Sorry for that.

No problems

**Pull request closed without merging**
